### ISSUE TITLE
Syntax highlighter

### ISSUE THREAD

**Issue by ElhemEnohpi** [StylishThemes/Wikipedia-Dark#131]
Not sure if this is a bug or a feature request, but if you have [syntax highlighting](https://www.mediawiki.org/wiki/User:Remember_the_dot/Syntax_highlighter) turned on for the wiki source editor (text editor, not visual editor), it's not darkened. You turn on syntax highlighting with: Preferences - Gadgets - Editing - Syntax highlighter

I can't figure out how to inspect the styles for the different highlights of the text in the box.

* **Browser**: Firefox 77
* **Operating System**: macOS 10.14
* **Link to page with the issue**: "edit source" on any Wikipedia page
* **Screenshot**:

**Comment by the-j0k3r** [comment]
> but if you have syntax highlighting turned on

I dont see this option, I see a few issues but nothing related.

Can you please show where?

Also, Im not logged in or have/want an account so bare that in mind.

**Comment by the-j0k3r** [comment]
Ah I see it, but its greyed out for me.

![Capture](https://user-images.githubusercontent.com/31389848/91277805-9e40cb80-e783-11ea-8d71-b9df4bb758b9.PNG)

**Comment by the-j0k3r** [comment]
Oh dang this is well hidden

![Capture](https://user-images.githubusercontent.com/31389848/91279280-9124dc00-e785-11ea-8e0c-1371e9bcb7b5.PNG)

This is ace editor domain, completely unstyled, so Ill consider this a feature request.

Will take a while to add this CSS.

**Comment by the-j0k3r** [comment]
https://github.com/StylishThemes/Wikipedia-Dark/issues/131 adds something towards this but lots still todo

fixed many issues not reported around this link but having some problems with 

![Capture](https://user-images.githubusercontent.com/31389848/91293490-609a6d80-e798-11ea-9742-6761213c7ce3.PNG)

@AfroThundr3007730 any thoughts?

**Comment by the-j0k3r** [comment]
3.4.16 should take care of this

**Comment by ElhemEnohpi** [comment]
@the-j0k3r thanks for working on this! Unfortunately it doesn't solve my issue/request. I've got 3.4.17 installed, but the text editor is still white. This is for the wiki _source text_ editor ("edit source" link), not the _visual editor_ ("edit" link) that is shown in your first screenshot. It's something you do need an account for, because (on [English Wikipedia](https://en.wikipedia.org)) it has to be enabled as a "gadget" in your Wikipedia account preferences: 

![screenshot_361](https://user-images.githubusercontent.com/23618559/92534199-7bf38700-f234-11ea-8318-8eb3dd0b6ca5.png)

Checking that box installs ["Remember the dot"'s script](https://www.mediawiki.org/wiki/User:Remember_the_dot/Syntax_highlighter#Source_code), the source code of which is [here.](https://www.mediawiki.org/wiki/User:Remember_the_dot/Syntax_highlighter.js) 

I'm not quite sure what I'm looking at in your second screenshot, but I guess it's part of the visual editor. I don't normally use the visual editor.

This is what the source text editor looks like, with Wikipedia Dark installed, and without the syntax highlighting enabled:

![screenshot_362](https://user-images.githubusercontent.com/23618559/92534152-5cf4f500-f234-11ea-99cb-38ab71e30297.png)

This is what it looks like with the syntax highlighting script enabled:

![screenshot_360](https://user-images.githubusercontent.com/23618559/92532466-a3e0eb80-f230-11ea-95d4-b34c0d8d06d7.png)

**Comment by the-j0k3r** [comment]
Sorry but cant duplicate

![generic](https://user-images.githubusercontent.com/31389848/92574903-fdc0d000-f287-11ea-9c6a-e90e9ce5dd5a.gif)

I see unrelated styling issues that will be fixed, but aside from that seems to work both visual editor and source editor mode.

Im also using Firefox but on Windows 10 not macOS, though I doubt this is an issue, I can test this scenario also.

Are you logged on, if so have you tried logged off also?

**Comment by ElhemEnohpi** [comment]
Ah, ok, I forgot about that button. It's something they added a couple of years ago. I never used it because I found it ugly compared to the existing "gadget", the script from "Remember the dot" which I linked to in my first post. You need to be logged in to an account, because it has to be enabled in the account preferences as shown in the first screenshot.

I've been using it for many years, and would really like to continue. But I can understand if it's not worth your while to support it. I'll try switching to the other one, it will take some getting used to. Maybe I can customize it somehow. Otherwise I could keep using Dark Reader, which works but is very slow.
