### ISSUE TITLE
Hover tooltips have white background

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#156]
* **Browser**: Chromium 87.0.4280.67
* **Operating System**: Lubuntu 20.04.1
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Main_Page
* **Screenshot**:

![1](https://user-images.githubusercontent.com/14265316/104937735-2fc50a00-59bf-11eb-95cf-b06629fb2fb3.png)

**Comment by MLavrentyev** [comment]
Same on Firefox 84.0.2 on both macOS Big Sur and Catalina

**Comment by TheNormalestPeep** [comment]
Also happens on the latest version of Chrome for Windows 10

**Comment by the-j0k3r** [comment]
Its not OS or browser issue related, they updated their css and the classes no longer match.

**Comment by jason-wihardja** [comment]
I've made a pull request to fix this issue. This is how the page now looks in my browser.

![image](https://user-images.githubusercontent.com/3488460/105580923-eb23df00-5dc1-11eb-9a1d-0e0c63b1bfc7.png)

Kindly review the code. Thanks!

**Comment by the-j0k3r** [comment]
fixed then by https://github.com/StylishThemes/Wikipedia-Dark/commit/8cd3388d0c51419c91f5c3fee923ceed2f1a041e

**Comment by TotalCaesar659** [comment]
I hate to re-open issues, but it's not fixed on mobile pages:
https://en.m.wikipedia.org/wiki/Main_Page
![1](https://user-images.githubusercontent.com/14265316/105633541-35f93180-5e6a-11eb-8000-b8c88d9d565e.png)

**Comment by jason-wihardja** [comment]
@TotalCaesar659 can you check using the code in the pull request and see whether this one fixes it for you? Thanks

**Comment by TotalCaesar659** [comment]
@jason-wihardja LGTM.
![1](https://user-images.githubusercontent.com/14265316/105726644-56dd8780-5f3b-11eb-831d-88b1d4433ba0.png)
